name: Build Docker Image

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:        
      - name: CHECKOUT
        uses: actions/checkout@v2
      
      - name: SET UP QEMU
        uses: docker/setup-qemu-action@v1

      - name: SET UP DOCKER BUILDX
        uses: docker/setup-buildx-action@v1
      
      - name: LOGIN TO DOCKERHUB
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: SET OUTPUT
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF:10}
      
      - name: GET NGINX VERSION
        id: get_nginx_version
        run: |
          echo "::set-output name=nginx_version::${{ steps.vars.outputs.tag }}"
          
      - name: GET OPENSSL VERSION (LATEST)
        id: get_openssl_latest_version
        if: steps.get_nginx_version.outputs.nginx_version != ''
        run: |
          OPENSSL_LATEST_VERSION=$(curl -s "https://raw.githubusercontent.com/yuri-moe/package-version/master/OPENSSL")
          echo "::set-output name=openssl_version::${OPENSSL_LATEST_VERSION}"
          
      - name: BUILD AND PUSH
        uses: docker/build-push-action@v2
        if: steps.get_nginx_version.outputs.nginx_version != '' && steps.get_openssl_latest_version.outputs.openssl_version != ''
        with:
          file: ./Dockerfile
          context: .
          build-args: |
            NGINX_VERSION=${{ steps.get_nginx_version.outputs.nginx_version }}
            OPENSSL_VERSION=${{ steps.get_openssl_latest_version.outputs.openssl_version }}
          platforms: linux/arm64, linux/amd64
          push: true
          no-cache: true
          tags: |
            ${{ secrets.DOCKER_NS }}/teri-nginx:${{ steps.get_nginx_version.outputs.nginx_version }}
            ${{ secrets.DOCKER_NS }}/teri-nginx:latest
