name: Check Version

on:
  schedule:
    - cron: '0 2 * * *'

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Installing Dependencies
        run: |
          sudo apt-get install -y jq curl git
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      
      - name: Check Nginx Version
        run: |
          LATEST_VERSION=$(curl -k -s https://api.rua.dev/versions/latest/nginx | jq .data.version | sed s/\"//g)
          
          echo $LATEST_VERSION
          
          HAVE_TAG=false
          
          for tag in $(git tag); do
            if [  "$LATEST_VERSION" == "$tag" ]; then
              HAVE_TAG=true
            fi
          done

          if ! $HAVE_TAG; then
            git tag $LATEST_VERSION
            git push --tags
          fi
